<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?import javafx.scene.*?><?import javafx.collections.*?><?import javafx.scene.layout.*?><?import javafx.scene.control.*?><?import javafx.scene.text.*?><?import javafx.scene.image.*?><?import javafx.scene.shape.*?><?import javafx.scene.paint.*?><?import javafx.scene.web.*?><?import javafx.geometry.*?><?import java.lang.*?><?import org.develnext.jphp.ext.javafx.classes.data.*?><?import org.develnext.jphp.ext.javafx.support.*?><?import org.develnext.jphp.ext.javafx.support.control.*?><?import org.develnext.jphp.ext.game.support.*?><AnchorPane xmlns="http://javafx.com/javafx/8" xmlns:fx="http://javafx.com/fxml/1" AnchorPane.bottomAnchor="0" AnchorPane.leftAnchor="0" AnchorPane.rightAnchor="0" AnchorPane.topAnchor="0" focusTraversable="false" id="" maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="112" prefWidth="296" styleClass="">
  <children>
    <LabelEx alignment="CENTER_LEFT" autoSize="false" contentDisplay="LEFT" ellipsisString="..." focusTraversable="false" graphicTextGap="4" id="label" layoutX="16" layoutY="8" prefHeight="24" prefWidth="264" styleClass="label " text="Enter the name for " textAlignment="LEFT" underline="false" wrapText="false">
      <font>
        <Font name="System Regular" size="16"/>
      </font>
    </LabelEx>
    <Data cursor="DEFAULT" enabled="1" id="data-label" visible="1"/>
    <TextField alignment="CENTER_LEFT" editable="true" focusTraversable="true" id="edit" layoutX="8" layoutY="32" prefColumnCount="12" prefHeight="32" prefWidth="280" promptText="" styleClass="text-input text-field " text="">
      <font>
        <Font name="System Regular" size="12"/>
      </font>
    </TextField>
    <Data cursor="DEFAULT" enabled="1" id="data-edit" visible="1"/>
    <Button alignment="CENTER" contentDisplay="LEFT" ellipsisString="..." focusTraversable="true" graphicTextGap="4" id="cancel" layoutX="16" layoutY="72" prefHeight="32" prefWidth="96" styleClass="button " text="Cancel" textAlignment="CENTER" underline="false" wrapText="false">
      <font>
        <Font name="System Regular" size="12"/>
      </font>
    </Button>
    <Data cursor="DEFAULT" enabled="1" graphic=".data/img/Delete.png" id="data-cancel" visible="1"/>
    <Button alignment="CENTER" contentDisplay="LEFT" ellipsisString="..." focusTraversable="true" graphicTextGap="4" id="make" layoutX="184" layoutY="72" prefHeight="32" prefWidth="96" styleClass="button " text="Make" textAlignment="CENTER" underline="false" wrapText="false">
      <font>
        <Font name="System Regular" size="12"/>
      </font>
    </Button>
    <Data cursor="DEFAULT" enabled="1" graphic=".data/img/success.png" id="data-make" visible="1"/>
  </children>
</AnchorPane>
